### ISSUE TITLE
segment.bytes passed via values.yaml is not getting updated in Kafka

### ISSUE THREAD

**Issue by anandkolli** [bitnami/bitnami-docker-kafka#62]
**Description**

Configuration of segment bytes via values.yaml is not reflecting as part of Kafka configuration.

**Steps to reproduce the issue:**

1. Update values.Yaml (logSegmentBytes: _250000000)
2. Deploy Kafka

**Describe the results you received:**
Value consumed by Kafka is the default value i.e. 1073741824
**log.segment.bytes = 1073741824**

**Additional information you deem important (e.g. issue happens only occasionally):**
And following is my observation w.r.t. the issue
1) Values passed as part of values.yaml is properly reflected inside the Kafka container.
```
printenv | grep 250000000
KAFKA_CFG_SEGMENT_BYTES=250000000
```
2) While populating configuration file server.properties field name passed is segment.bytes=250000000
instead, field name should have been passed as **log.segment.bytes=250000000**

**Version**
2.2.1-debian-9-r12

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
- We are using Kubernetes environment to deploy Kafka.

**Comment by marcosbc** [comment]
Hi @anandkolli, thanks for reporting this. We should be using `log.segment.bytes` as `segment.bytes` is meant for topic-specific configurations: https://kafka.apache.org/documentation/#topicconfigs

We're working on fixing this and will let you know of the progress.

**Comment by marcosbc** [comment]
Hi, just wanted to let you know we released Kafka `2.3.0-debian-9-r66` and `2.3.0-ol-7-r72` which fixes this issue.

I'm closing this as it was solved, but feel free to add any question.

**Comment by anandkolli** [comment]
Thank you :)

**Comment by ananthprasads** [comment]
@marcosbc Looks like issue not resolved. Though it is configuring in server.properties, issue still persists in kubectl logs.
Following is server.properties
log.retention.check.intervals.ms=300000
max.message.bytes=1000012
port=9092
segment.bytes=500000000
ssl.endpoint.identification.algorithm=https

Pod Description:
I am using new image
  Type    Reason                 Age                From               Message
  ----    ------                 ----               ----               -------
  Normal  Scheduled              37m                default-scheduler  Successfully assigned internal-kafka-0 to demo1
  Normal  SuccessfulMountVolume  37m                kubelet, demo1     MountVolume.SetUp succeeded for volume "tz-config"
  Normal  SuccessfulMountVolume  37m                kubelet, demo1     MountVolume.SetUp succeeded for volume "default-token-thw7m"
  Normal  SuccessfulMountVolume  37m (x2 over 37m)  kubelet, demo1     MountVolume.SetUp succeeded for volume "internal-kafka-kafka-pv2"
  Normal  Pulling                37m                kubelet, demo1     pulling image "docker-registry.com:5000/bitnami/kafka:2.3.0-debian-9-r66"
  Normal  Pulled                 37m                kubelet, demo1     Successfully pulled image "docker-registry.com:5000/bitnami/kafka:2.3.0-debian-9-r66"

Kubectl logs output:
log.roll.jitter.hours = 0
        log.roll.jitter.ms = null
        log.roll.ms = null
        log.segment.bytes = 1073741824

**Comment by marcosbc** [comment]
You are right @ananthprasads. We have been able to reproduce this issue and are working on fixing it. Thanks for reporting it!

**Comment by marcosbc** [comment]
Hi @ananthprasads, just wanted to let you know that we updated the chart and set the proper values for the environment variables.
