### ISSUE TITLE
kafka container out of memory on ubuntu over azure

### ISSUE THREAD

**Issue by daveonrail** [bitnami/bitnami-docker-kafka#82]
I deployed a zookeeper and a kafka container on VM ware playre VM with ubuntu 18.04 server machine and docker 19.03.4.

All works without problem, and thi VM is very low HW (2GB).

Then i deployed the same containers on an ubuntu 18.04 hosted on azure and after some minutes of working the kafka container restart due to out of memory.

I tried some solution found on several topics on the net without success.

Below you can find the docker compose used on both configuration.

I hope you can help me, thank you

Best regards

Dave

version: '2.4'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    container_name: zookeeper
    ports:
     - "${EXPOSED_IP_ADDRESS:-0.0.0.0}:2181:2181"
    volumes:
      - '/path/zookeeper:/bitnami/zookeeper'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-net
    restart: on-failure:5
    mem_limit: 512m
    cpu_percent: 25
    cpu_shares: 1024
    security_opt:
      - no-new-privileges
    pids_limit: 1000

  kafka:
    image: 'bitnami/kafka:2'
    container_name: kafka
    ports:
      - "${EXPOSED_IP_ADDRESS:-0.0.0.0}:9092:9092"
    volumes:
      - /path/kafka/:/bitnami/kafka
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "(kafka-topics.sh --zookeeper zookeeper:2181 --list) || exit 1"]
      interval: 15s
      timeout: 70s
      retries: 15
      start_period: 15s
    networks:
      - my-net
    restart: on-failure:5
    mem_limit: 512m
    # memswap_limit: 512m
    cpu_percent: 25
    cpu_shares: 1024
    security_opt:
      - no-new-privileges
    pids_limit: 1000

**Comment by javsalgar** [comment]
Hi,

Just to confirm, could it be that 512Mb is a very low amount of memory? How much consumption did it get on the original machine? Did you try increasing that limit?

**Comment by daveonrail** [comment]
I don't think because on the original machine, the entire VM has just 2Gb
of memory and the containers use very low amount, in fact I also tried, on
the original VM to limit the container memory to just 128Mb and it still
works.


Thanks

Il giorno gio 16 gen 2020 alle ore 10:38 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
Is it using the same Docker version in both of them? I do not know if there's any other differences in the kernel version or in the underlying virtualization technology that could be causing this.  Anyways, it seems very weird to me that the container may work with just 128 Mb.

**Comment by daveonrail** [comment]
Are two minor version

Working VM is Docker version 19.03.4, build 9013bf583a
Azure VM is Docker version 19.03.5, build 633a0ea838

Now I set up the environment variable for the container
KAFKA_HEAP_OPTS=-Xmx1024m -Xms512m
and when the container started the first time it took 470Mb of memory, but
that amount increase constantly, in fact in 2 days it reach 720Mb

Thanks for support

Il giorno lun 20 gen 2020 alle ore 12:23 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
Hi,

And how much activity does Kafka have? How many writers and subscribers?

**Comment by daveonrail** [comment]
Hi,
6 writer and 7 subscriber. But now I just keep the kafka and zookeepr
containers up and running to exclude that third party behavior could give
problems in find the issue.

Il giorno gio 23 gen 2020 alle ore 11:03 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
What do you exactly mean by third party behavior? Did you disable the writers and subscribers?

**Comment by daveonrail** [comment]
Yes exactly, i just deployed the kafka and zookepper container

Il giorno gio 23 gen 2020 alle ore 18:16 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
And still the same issue happens or in this case it doesn't?

**Comment by daveonrail** [comment]
The same issue continue to happens.

BR

Il giorno ven 24 gen 2020 alle ore 17:26 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
And after how long does the memory becomes too high?

**Comment by daveonrail** [comment]
It increase about 100Mb at day

Il giorno lun 3 feb 2020 alle ore 13:49 Javier J. Salmerón-García <
notifications@github.com> ha scritto:

**Comment by javsalgar** [comment]
Doesn't it stabilize at some point? Do the logs show anything meaningful? I'm trying to think of something that may be different in one system and the other. Because you say that, even after long time, the 100Mb per day issue does not happen in your local system, right? 

Just came to my mind, is there a huge amount of logging in the container?
